// Server-to-server read API that challenger-service exposes to
// challenger-notification-service. challenger-service owns this contract; the
// notification service mirrors the file byte-for-byte. A breaking change is a
// new v2 package, never an in-place edit (buf breaking guards this in CI).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: challenger/internalv1/challenge.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChallengeStatus is the admin-managed publication state.
type ChallengeStatus int32

const (
	ChallengeStatus_CHALLENGE_STATUS_UNSPECIFIED ChallengeStatus = 0
	ChallengeStatus_CHALLENGE_STATUS_PRIVATE     ChallengeStatus = 1
	ChallengeStatus_CHALLENGE_STATUS_PUBLISH     ChallengeStatus = 2
)

// Enum value maps for ChallengeStatus.
var (
	ChallengeStatus_name = map[int32]string{
		0: "CHALLENGE_STATUS_UNSPECIFIED",
		1: "CHALLENGE_STATUS_PRIVATE",
		2: "CHALLENGE_STATUS_PUBLISH",
	}
	ChallengeStatus_value = map[string]int32{
		"CHALLENGE_STATUS_UNSPECIFIED": 0,
		"CHALLENGE_STATUS_PRIVATE":     1,
		"CHALLENGE_STATUS_PUBLISH":     2,
	}
)

func (x ChallengeStatus) Enum() *ChallengeStatus {
	p := new(ChallengeStatus)
	*p = x
	return p
}

func (x ChallengeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChallengeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_challenger_internalv1_challenge_proto_enumTypes[0].Descriptor()
}

func (ChallengeStatus) Type() protoreflect.EnumType {
	return &file_challenger_internalv1_challenge_proto_enumTypes[0]
}

func (x ChallengeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChallengeStatus.Descriptor instead.
func (ChallengeStatus) EnumDescriptor() ([]byte, []int) {
	return file_challenger_internalv1_challenge_proto_rawDescGZIP(), []int{0}
}

// AccessDeniedReason explains why available = false.
type AccessDeniedReason int32

const (
	// available = true.
	AccessDeniedReason_ACCESS_DENIED_REASON_UNSPECIFIED     AccessDeniedReason = 0
	AccessDeniedReason_ACCESS_DENIED_REASON_NOT_FOUND       AccessDeniedReason = 1
	AccessDeniedReason_ACCESS_DENIED_REASON_DELETED         AccessDeniedReason = 2
	AccessDeniedReason_ACCESS_DENIED_REASON_NOT_WHITELISTED AccessDeniedReason = 3
)

// Enum value maps for AccessDeniedReason.
var (
	AccessDeniedReason_name = map[int32]string{
		0: "ACCESS_DENIED_REASON_UNSPECIFIED",
		1: "ACCESS_DENIED_REASON_NOT_FOUND",
		2: "ACCESS_DENIED_REASON_DELETED",
		3: "ACCESS_DENIED_REASON_NOT_WHITELISTED",
	}
	AccessDeniedReason_value = map[string]int32{
		"ACCESS_DENIED_REASON_UNSPECIFIED":     0,
		"ACCESS_DENIED_REASON_NOT_FOUND":       1,
		"ACCESS_DENIED_REASON_DELETED":         2,
		"ACCESS_DENIED_REASON_NOT_WHITELISTED": 3,
	}
)

func (x AccessDeniedReason) Enum() *AccessDeniedReason {
	p := new(AccessDeniedReason)
	*p = x
	return p
}

func (x AccessDeniedReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessDeniedReason) Descriptor() protoreflect.EnumDescriptor {
	return file_challenger_internalv1_challenge_proto_enumTypes[1].Descriptor()
}

func (AccessDeniedReason) Type() protoreflect.EnumType {
	return &file_challenger_internalv1_challenge_proto_enumTypes[1]
}

func (x AccessDeniedReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessDeniedReason.Descriptor instead.
func (AccessDeniedReason) EnumDescriptor() ([]byte, []int) {
	return file_challenger_internalv1_challenge_proto_rawDescGZIP(), []int{1}
}

// Challenge is the notification-facing view of a challenge.
type Challenge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 24-hex ObjectID.
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status   ChallengeStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=challenger.internal.v1.ChallengeStatus" json:"status,omitempty"`
	StartsAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	// CloudFront-rewritten, same as the public API.
	ThumbnailUrl string `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	// New CMS field; falls back to the description until the CMS ships it.
	ShortDescription string `protobuf:"bytes,7,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	// New CMS field; falls back to the description until the CMS ships it.
	Tagline       string `protobuf:"bytes,8,opt,name=tagline,proto3" json:"tagline,omitempty"`
	Deleted       bool   `protobuf:"varint,9,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_challenge_proto_rawDescGZIP(), []int{0}
}

func (x *Challenge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Challenge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Challenge) GetStatus() ChallengeStatus {
	if x != nil {
		return x.Status
	}
	return ChallengeStatus_CHALLENGE_STATUS_UNSPECIFIED
}

func (x *Challenge) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *Challenge) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *Challenge) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Challenge) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *Challenge) GetTagline() string {
	if x != nil {
		return x.Tagline
	}
	return ""
}

func (x *Challenge) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// GetChallengeRequest identifies the challenge by its 24-hex ObjectID.
type GetChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeRequest) Reset() {
	*x = GetChallengeRequest{}
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeRequest) ProtoMessage() {}

func (x *GetChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeRequest.ProtoReflect.Descriptor instead.
func (*GetChallengeRequest) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_challenge_proto_rawDescGZIP(), []int{1}
}

func (x *GetChallengeRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

// GetChallengeResponse carries the challenge.
type GetChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     *Challenge             `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeResponse) Reset() {
	*x = GetChallengeResponse{}
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeResponse) ProtoMessage() {}

func (x *GetChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeResponse.ProtoReflect.Descriptor instead.
func (*GetChallengeResponse) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_challenge_proto_rawDescGZIP(), []int{2}
}

func (x *GetChallengeResponse) GetChallenge() *Challenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

// ListLifecycleChallengesRequest takes no filter; the window is server-defined.
type ListLifecycleChallengesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLifecycleChallengesRequest) Reset() {
	*x = ListLifecycleChallengesRequest{}
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLifecycleChallengesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLifecycleChallengesRequest) ProtoMessage() {}

func (x *ListLifecycleChallengesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLifecycleChallengesRequest.ProtoReflect.Descriptor instead.
func (*ListLifecycleChallengesRequest) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_challenge_proto_rawDescGZIP(), []int{3}
}

// ListLifecycleChallengesResponse carries the live challenges.
type ListLifecycleChallengesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenges    []*Challenge           `protobuf:"bytes,1,rep,name=challenges,proto3" json:"challenges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLifecycleChallengesResponse) Reset() {
	*x = ListLifecycleChallengesResponse{}
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLifecycleChallengesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLifecycleChallengesResponse) ProtoMessage() {}

func (x *ListLifecycleChallengesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLifecycleChallengesResponse.ProtoReflect.Descriptor instead.
func (*ListLifecycleChallengesResponse) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_challenge_proto_rawDescGZIP(), []int{4}
}

func (x *ListLifecycleChallengesResponse) GetChallenges() []*Challenge {
	if x != nil {
		return x.Challenges
	}
	return nil
}

// CheckChallengeAccessRequest pairs a challenge with the user opening it.
type CheckChallengeAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckChallengeAccessRequest) Reset() {
	*x = CheckChallengeAccessRequest{}
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckChallengeAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckChallengeAccessRequest) ProtoMessage() {}

func (x *CheckChallengeAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckChallengeAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckChallengeAccessRequest) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_challenge_proto_rawDescGZIP(), []int{5}
}

func (x *CheckChallengeAccessRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *CheckChallengeAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ListNotifySubscriberIDsRequest pages one challenge's subscribers.
type ListNotifySubscriberIDsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// 0 means 1000; larger values are capped at 1000; negative is rejected.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque; empty starts from the beginning.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotifySubscriberIDsRequest) Reset() {
	*x = ListNotifySubscriberIDsRequest{}
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotifySubscriberIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotifySubscriberIDsRequest) ProtoMessage() {}

func (x *ListNotifySubscriberIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotifySubscriberIDsRequest.ProtoReflect.Descriptor instead.
func (*ListNotifySubscriberIDsRequest) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_challenge_proto_rawDescGZIP(), []int{6}
}

func (x *ListNotifySubscriberIDsRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ListNotifySubscriberIDsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNotifySubscriberIDsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListNotifySubscriberIDsResponse is one page of subscriber user ids.
type ListNotifySubscriberIDsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	UserIds []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	// Empty when there are no more rows.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotifySubscriberIDsResponse) Reset() {
	*x = ListNotifySubscriberIDsResponse{}
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotifySubscriberIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotifySubscriberIDsResponse) ProtoMessage() {}

func (x *ListNotifySubscriberIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotifySubscriberIDsResponse.ProtoReflect.Descriptor instead.
func (*ListNotifySubscriberIDsResponse) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_challenge_proto_rawDescGZIP(), []int{7}
}

func (x *ListNotifySubscriberIDsResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *ListNotifySubscriberIDsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// CheckChallengeAccessResponse is the access verdict.
type CheckChallengeAccessResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Available bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Reason    AccessDeniedReason     `protobuf:"varint,2,opt,name=reason,proto3,enum=challenger.internal.v1.AccessDeniedReason" json:"reason,omitempty"`
	// now >= ends_at; the caller navigates to the leaderboard instead of detail.
	Ended         bool `protobuf:"varint,3,opt,name=ended,proto3" json:"ended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckChallengeAccessResponse) Reset() {
	*x = CheckChallengeAccessResponse{}
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckChallengeAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckChallengeAccessResponse) ProtoMessage() {}

func (x *CheckChallengeAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_challenge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckChallengeAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckChallengeAccessResponse) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_challenge_proto_rawDescGZIP(), []int{8}
}

func (x *CheckChallengeAccessResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckChallengeAccessResponse) GetReason() AccessDeniedReason {
	if x != nil {
		return x.Reason
	}
	return AccessDeniedReason_ACCESS_DENIED_REASON_UNSPECIFIED
}

func (x *CheckChallengeAccessResponse) GetEnded() bool {
	if x != nil {
		return x.Ended
	}
	return false
}

var File_challenger_internalv1_challenge_proto protoreflect.FileDescriptor

const file_challenger_internalv1_challenge_proto_rawDesc = "" +
	"\n" +
	"%challenger/internalv1/challenge.proto\x12\x16challenger.internal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x02\n" +
	"\tChallenge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12?\n" +
	"\x06status\x18\x03 \x01(\x0e2'.challenger.internal.v1.ChallengeStatusR\x06status\x127\n" +
	"\tstarts_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x12#\n" +
	"\rthumbnail_url\x18\x06 \x01(\tR\fthumbnailUrl\x12+\n" +
	"\x11short_description\x18\a \x01(\tR\x10shortDescription\x12\x18\n" +
	"\atagline\x18\b \x01(\tR\atagline\x12\x18\n" +
	"\adeleted\x18\t \x01(\bR\adeleted\"8\n" +
	"\x13GetChallengeRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\"W\n" +
	"\x14GetChallengeResponse\x12?\n" +
	"\tchallenge\x18\x01 \x01(\v2!.challenger.internal.v1.ChallengeR\tchallenge\" \n" +
	"\x1eListLifecycleChallengesRequest\"d\n" +
	"\x1fListLifecycleChallengesResponse\x12A\n" +
	"\n" +
	"challenges\x18\x01 \x03(\v2!.challenger.internal.v1.ChallengeR\n" +
	"challenges\"Y\n" +
	"\x1bCheckChallengeAccessRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x7f\n" +
	"\x1eListNotifySubscriberIDsRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"d\n" +
	"\x1fListNotifySubscriberIDsResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x96\x01\n" +
	"\x1cCheckChallengeAccessResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12B\n" +
	"\x06reason\x18\x02 \x01(\x0e2*.challenger.internal.v1.AccessDeniedReasonR\x06reason\x12\x14\n" +
	"\x05ended\x18\x03 \x01(\bR\x05ended*o\n" +
	"\x0fChallengeStatus\x12 \n" +
	"\x1cCHALLENGE_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CHALLENGE_STATUS_PRIVATE\x10\x01\x12\x1c\n" +
	"\x18CHALLENGE_STATUS_PUBLISH\x10\x02*\xaa\x01\n" +
	"\x12AccessDeniedReason\x12$\n" +
	" ACCESS_DENIED_REASON_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eACCESS_DENIED_REASON_NOT_FOUND\x10\x01\x12 \n" +
	"\x1cACCESS_DENIED_REASON_DELETED\x10\x02\x12(\n" +
	"$ACCESS_DENIED_REASON_NOT_WHITELISTED\x10\x032\xa3\x04\n" +
	"\x18ChallengeInternalService\x12i\n" +
	"\fGetChallenge\x12+.challenger.internal.v1.GetChallengeRequest\x1a,.challenger.internal.v1.GetChallengeResponse\x12\x8a\x01\n" +
	"\x17ListLifecycleChallenges\x126.challenger.internal.v1.ListLifecycleChallengesRequest\x1a7.challenger.internal.v1.ListLifecycleChallengesResponse\x12\x81\x01\n" +
	"\x14CheckChallengeAccess\x123.challenger.internal.v1.CheckChallengeAccessRequest\x1a4.challenger.internal.v1.CheckChallengeAccessResponse\x12\x8a\x01\n" +
	"\x17ListNotifySubscriberIDs\x126.challenger.internal.v1.ListNotifySubscriberIDsRequest\x1a7.challenger.internal.v1.ListNotifySubscriberIDsResponseBQZOgithub.com/Everfit-io/challenger-service/proto/challenger/internalv1;internalv1b\x06proto3"

var (
	file_challenger_internalv1_challenge_proto_rawDescOnce sync.Once
	file_challenger_internalv1_challenge_proto_rawDescData []byte
)

func file_challenger_internalv1_challenge_proto_rawDescGZIP() []byte {
	file_challenger_internalv1_challenge_proto_rawDescOnce.Do(func() {
		file_challenger_internalv1_challenge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_challenger_internalv1_challenge_proto_rawDesc), len(file_challenger_internalv1_challenge_proto_rawDesc)))
	})
	return file_challenger_internalv1_challenge_proto_rawDescData
}

var file_challenger_internalv1_challenge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_challenger_internalv1_challenge_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_challenger_internalv1_challenge_proto_goTypes = []any{
	(ChallengeStatus)(0),                    // 0: challenger.internal.v1.ChallengeStatus
	(AccessDeniedReason)(0),                 // 1: challenger.internal.v1.AccessDeniedReason
	(*Challenge)(nil),                       // 2: challenger.internal.v1.Challenge
	(*GetChallengeRequest)(nil),             // 3: challenger.internal.v1.GetChallengeRequest
	(*GetChallengeResponse)(nil),            // 4: challenger.internal.v1.GetChallengeResponse
	(*ListLifecycleChallengesRequest)(nil),  // 5: challenger.internal.v1.ListLifecycleChallengesRequest
	(*ListLifecycleChallengesResponse)(nil), // 6: challenger.internal.v1.ListLifecycleChallengesResponse
	(*CheckChallengeAccessRequest)(nil),     // 7: challenger.internal.v1.CheckChallengeAccessRequest
	(*ListNotifySubscriberIDsRequest)(nil),  // 8: challenger.internal.v1.ListNotifySubscriberIDsRequest
	(*ListNotifySubscriberIDsResponse)(nil), // 9: challenger.internal.v1.ListNotifySubscriberIDsResponse
	(*CheckChallengeAccessResponse)(nil),    // 10: challenger.internal.v1.CheckChallengeAccessResponse
	(*timestamppb.Timestamp)(nil),           // 11: google.protobuf.Timestamp
}
var file_challenger_internalv1_challenge_proto_depIdxs = []int32{
	0,  // 0: challenger.internal.v1.Challenge.status:type_name -> challenger.internal.v1.ChallengeStatus
	11, // 1: challenger.internal.v1.Challenge.starts_at:type_name -> google.protobuf.Timestamp
	11, // 2: challenger.internal.v1.Challenge.ends_at:type_name -> google.protobuf.Timestamp
	2,  // 3: challenger.internal.v1.GetChallengeResponse.challenge:type_name -> challenger.internal.v1.Challenge
	2,  // 4: challenger.internal.v1.ListLifecycleChallengesResponse.challenges:type_name -> challenger.internal.v1.Challenge
	1,  // 5: challenger.internal.v1.CheckChallengeAccessResponse.reason:type_name -> challenger.internal.v1.AccessDeniedReason
	3,  // 6: challenger.internal.v1.ChallengeInternalService.GetChallenge:input_type -> challenger.internal.v1.GetChallengeRequest
	5,  // 7: challenger.internal.v1.ChallengeInternalService.ListLifecycleChallenges:input_type -> challenger.internal.v1.ListLifecycleChallengesRequest
	7,  // 8: challenger.internal.v1.ChallengeInternalService.CheckChallengeAccess:input_type -> challenger.internal.v1.CheckChallengeAccessRequest
	8,  // 9: challenger.internal.v1.ChallengeInternalService.ListNotifySubscriberIDs:input_type -> challenger.internal.v1.ListNotifySubscriberIDsRequest
	4,  // 10: challenger.internal.v1.ChallengeInternalService.GetChallenge:output_type -> challenger.internal.v1.GetChallengeResponse
	6,  // 11: challenger.internal.v1.ChallengeInternalService.ListLifecycleChallenges:output_type -> challenger.internal.v1.ListLifecycleChallengesResponse
	10, // 12: challenger.internal.v1.ChallengeInternalService.CheckChallengeAccess:output_type -> challenger.internal.v1.CheckChallengeAccessResponse
	9,  // 13: challenger.internal.v1.ChallengeInternalService.ListNotifySubscriberIDs:output_type -> challenger.internal.v1.ListNotifySubscriberIDsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_challenger_internalv1_challenge_proto_init() }
func file_challenger_internalv1_challenge_proto_init() {
	if File_challenger_internalv1_challenge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_challenger_internalv1_challenge_proto_rawDesc), len(file_challenger_internalv1_challenge_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_challenger_internalv1_challenge_proto_goTypes,
		DependencyIndexes: file_challenger_internalv1_challenge_proto_depIdxs,
		EnumInfos:         file_challenger_internalv1_challenge_proto_enumTypes,
		MessageInfos:      file_challenger_internalv1_challenge_proto_msgTypes,
	}.Build()
	File_challenger_internalv1_challenge_proto = out.File
	file_challenger_internalv1_challenge_proto_goTypes = nil
	file_challenger_internalv1_challenge_proto_depIdxs = nil
}
