// Server-to-server read API that challenger-service exposes to
// challenger-notification-service. challenger-service owns this contract; the
// notification service mirrors the file byte-for-byte. A breaking change is a
// new v2 package, never an in-place edit (buf breaking guards this in CI).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: challenger/internalv1/challenge.proto

package internalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChallengeInternalService_GetChallenge_FullMethodName            = "/challenger.internal.v1.ChallengeInternalService/GetChallenge"
	ChallengeInternalService_ListLifecycleChallenges_FullMethodName = "/challenger.internal.v1.ChallengeInternalService/ListLifecycleChallenges"
	ChallengeInternalService_CheckChallengeAccess_FullMethodName    = "/challenger.internal.v1.ChallengeInternalService/CheckChallengeAccess"
	ChallengeInternalService_ListNotifySubscriberIDs_FullMethodName = "/challenger.internal.v1.ChallengeInternalService/ListNotifySubscriberIDs"
)

// ChallengeInternalServiceClient is the client API for ChallengeInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChallengeInternalService serves challenge reads for the notification service.
// Every RPC requires the internal-api-secret metadata.
type ChallengeInternalServiceClient interface {
	// GetChallenge returns the challenge in ANY status, including soft-deleted
	// (deleted = true). NOT_FOUND only when the id never existed.
	GetChallenge(ctx context.Context, in *GetChallengeRequest, opts ...grpc.CallOption) (*GetChallengeResponse, error)
	// ListLifecycleChallenges returns every non-deleted private or publish
	// challenge whose ends_at is later than now - 24h. Bounded by the number of
	// live challenges (single digits), so not paginated.
	ListLifecycleChallenges(ctx context.Context, in *ListLifecycleChallengesRequest, opts ...grpc.CallOption) (*ListLifecycleChallengesResponse, error)
	// CheckChallengeAccess answers "may this user open the challenge now".
	CheckChallengeAccess(ctx context.Context, in *CheckChallengeAccessRequest, opts ...grpc.CallOption) (*CheckChallengeAccessResponse, error)
	// ListNotifySubscriberIDs pages the users who tapped "Notify me" on a
	// challenge, in subscription order. An unknown challenge has no subscribers.
	ListNotifySubscriberIDs(ctx context.Context, in *ListNotifySubscriberIDsRequest, opts ...grpc.CallOption) (*ListNotifySubscriberIDsResponse, error)
}

type challengeInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChallengeInternalServiceClient(cc grpc.ClientConnInterface) ChallengeInternalServiceClient {
	return &challengeInternalServiceClient{cc}
}

func (c *challengeInternalServiceClient) GetChallenge(ctx context.Context, in *GetChallengeRequest, opts ...grpc.CallOption) (*GetChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChallengeResponse)
	err := c.cc.Invoke(ctx, ChallengeInternalService_GetChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *challengeInternalServiceClient) ListLifecycleChallenges(ctx context.Context, in *ListLifecycleChallengesRequest, opts ...grpc.CallOption) (*ListLifecycleChallengesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLifecycleChallengesResponse)
	err := c.cc.Invoke(ctx, ChallengeInternalService_ListLifecycleChallenges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *challengeInternalServiceClient) CheckChallengeAccess(ctx context.Context, in *CheckChallengeAccessRequest, opts ...grpc.CallOption) (*CheckChallengeAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckChallengeAccessResponse)
	err := c.cc.Invoke(ctx, ChallengeInternalService_CheckChallengeAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *challengeInternalServiceClient) ListNotifySubscriberIDs(ctx context.Context, in *ListNotifySubscriberIDsRequest, opts ...grpc.CallOption) (*ListNotifySubscriberIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotifySubscriberIDsResponse)
	err := c.cc.Invoke(ctx, ChallengeInternalService_ListNotifySubscriberIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChallengeInternalServiceServer is the server API for ChallengeInternalService service.
// All implementations must embed UnimplementedChallengeInternalServiceServer
// for forward compatibility.
//
// ChallengeInternalService serves challenge reads for the notification service.
// Every RPC requires the internal-api-secret metadata.
type ChallengeInternalServiceServer interface {
	// GetChallenge returns the challenge in ANY status, including soft-deleted
	// (deleted = true). NOT_FOUND only when the id never existed.
	GetChallenge(context.Context, *GetChallengeRequest) (*GetChallengeResponse, error)
	// ListLifecycleChallenges returns every non-deleted private or publish
	// challenge whose ends_at is later than now - 24h. Bounded by the number of
	// live challenges (single digits), so not paginated.
	ListLifecycleChallenges(context.Context, *ListLifecycleChallengesRequest) (*ListLifecycleChallengesResponse, error)
	// CheckChallengeAccess answers "may this user open the challenge now".
	CheckChallengeAccess(context.Context, *CheckChallengeAccessRequest) (*CheckChallengeAccessResponse, error)
	// ListNotifySubscriberIDs pages the users who tapped "Notify me" on a
	// challenge, in subscription order. An unknown challenge has no subscribers.
	ListNotifySubscriberIDs(context.Context, *ListNotifySubscriberIDsRequest) (*ListNotifySubscriberIDsResponse, error)
	mustEmbedUnimplementedChallengeInternalServiceServer()
}

// UnimplementedChallengeInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChallengeInternalServiceServer struct{}

func (UnimplementedChallengeInternalServiceServer) GetChallenge(context.Context, *GetChallengeRequest) (*GetChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChallenge not implemented")
}
func (UnimplementedChallengeInternalServiceServer) ListLifecycleChallenges(context.Context, *ListLifecycleChallengesRequest) (*ListLifecycleChallengesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLifecycleChallenges not implemented")
}
func (UnimplementedChallengeInternalServiceServer) CheckChallengeAccess(context.Context, *CheckChallengeAccessRequest) (*CheckChallengeAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckChallengeAccess not implemented")
}
func (UnimplementedChallengeInternalServiceServer) ListNotifySubscriberIDs(context.Context, *ListNotifySubscriberIDsRequest) (*ListNotifySubscriberIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotifySubscriberIDs not implemented")
}
func (UnimplementedChallengeInternalServiceServer) mustEmbedUnimplementedChallengeInternalServiceServer() {
}
func (UnimplementedChallengeInternalServiceServer) testEmbeddedByValue() {}

// UnsafeChallengeInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChallengeInternalServiceServer will
// result in compilation errors.
type UnsafeChallengeInternalServiceServer interface {
	mustEmbedUnimplementedChallengeInternalServiceServer()
}

func RegisterChallengeInternalServiceServer(s grpc.ServiceRegistrar, srv ChallengeInternalServiceServer) {
	// If the following call panics, it indicates UnimplementedChallengeInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChallengeInternalService_ServiceDesc, srv)
}

func _ChallengeInternalService_GetChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengeInternalServiceServer).GetChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChallengeInternalService_GetChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengeInternalServiceServer).GetChallenge(ctx, req.(*GetChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChallengeInternalService_ListLifecycleChallenges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLifecycleChallengesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengeInternalServiceServer).ListLifecycleChallenges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChallengeInternalService_ListLifecycleChallenges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengeInternalServiceServer).ListLifecycleChallenges(ctx, req.(*ListLifecycleChallengesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChallengeInternalService_CheckChallengeAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckChallengeAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengeInternalServiceServer).CheckChallengeAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChallengeInternalService_CheckChallengeAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengeInternalServiceServer).CheckChallengeAccess(ctx, req.(*CheckChallengeAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChallengeInternalService_ListNotifySubscriberIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotifySubscriberIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengeInternalServiceServer).ListNotifySubscriberIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChallengeInternalService_ListNotifySubscriberIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengeInternalServiceServer).ListNotifySubscriberIDs(ctx, req.(*ListNotifySubscriberIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChallengeInternalService_ServiceDesc is the grpc.ServiceDesc for ChallengeInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChallengeInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "challenger.internal.v1.ChallengeInternalService",
	HandlerType: (*ChallengeInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChallenge",
			Handler:    _ChallengeInternalService_GetChallenge_Handler,
		},
		{
			MethodName: "ListLifecycleChallenges",
			Handler:    _ChallengeInternalService_ListLifecycleChallenges_Handler,
		},
		{
			MethodName: "CheckChallengeAccess",
			Handler:    _ChallengeInternalService_CheckChallengeAccess_Handler,
		},
		{
			MethodName: "ListNotifySubscriberIDs",
			Handler:    _ChallengeInternalService_ListNotifySubscriberIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "challenger/internalv1/challenge.proto",
}
