// Server-to-server read API that challenger-service exposes to
// challenger-notification-service. challenger-service owns this contract; the
// notification service mirrors the file byte-for-byte. A breaking change is a
// new v2 package, never an in-place edit (buf breaking guards this in CI).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: challenger/internalv1/leaderboard.proto

package internalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeaderboardInternalService_ListParticipants_FullMethodName = "/challenger.internal.v1.LeaderboardInternalService/ListParticipants"
)

// LeaderboardInternalServiceClient is the client API for LeaderboardInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LeaderboardInternalService serves leaderboard reads for the notification
// service. Every RPC requires the internal-api-secret metadata.
type LeaderboardInternalServiceClient interface {
	// ListParticipants pages every participant of a challenge in leaderboard
	// order, with the rank and points GET /leaderboards/{id} shows. An unknown
	// challenge, or one nobody has played, is an empty list with
	// total_participants = 0, not an error. UNAVAILABLE with reason
	// LEADERBOARD_REBUILDING while the leaderboard is being rebuilt; retry.
	ListParticipants(ctx context.Context, in *ListParticipantsRequest, opts ...grpc.CallOption) (*ListParticipantsResponse, error)
}

type leaderboardInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaderboardInternalServiceClient(cc grpc.ClientConnInterface) LeaderboardInternalServiceClient {
	return &leaderboardInternalServiceClient{cc}
}

func (c *leaderboardInternalServiceClient) ListParticipants(ctx context.Context, in *ListParticipantsRequest, opts ...grpc.CallOption) (*ListParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListParticipantsResponse)
	err := c.cc.Invoke(ctx, LeaderboardInternalService_ListParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaderboardInternalServiceServer is the server API for LeaderboardInternalService service.
// All implementations must embed UnimplementedLeaderboardInternalServiceServer
// for forward compatibility.
//
// LeaderboardInternalService serves leaderboard reads for the notification
// service. Every RPC requires the internal-api-secret metadata.
type LeaderboardInternalServiceServer interface {
	// ListParticipants pages every participant of a challenge in leaderboard
	// order, with the rank and points GET /leaderboards/{id} shows. An unknown
	// challenge, or one nobody has played, is an empty list with
	// total_participants = 0, not an error. UNAVAILABLE with reason
	// LEADERBOARD_REBUILDING while the leaderboard is being rebuilt; retry.
	ListParticipants(context.Context, *ListParticipantsRequest) (*ListParticipantsResponse, error)
	mustEmbedUnimplementedLeaderboardInternalServiceServer()
}

// UnimplementedLeaderboardInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaderboardInternalServiceServer struct{}

func (UnimplementedLeaderboardInternalServiceServer) ListParticipants(context.Context, *ListParticipantsRequest) (*ListParticipantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListParticipants not implemented")
}
func (UnimplementedLeaderboardInternalServiceServer) mustEmbedUnimplementedLeaderboardInternalServiceServer() {
}
func (UnimplementedLeaderboardInternalServiceServer) testEmbeddedByValue() {}

// UnsafeLeaderboardInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaderboardInternalServiceServer will
// result in compilation errors.
type UnsafeLeaderboardInternalServiceServer interface {
	mustEmbedUnimplementedLeaderboardInternalServiceServer()
}

func RegisterLeaderboardInternalServiceServer(s grpc.ServiceRegistrar, srv LeaderboardInternalServiceServer) {
	// If the following call panics, it indicates UnimplementedLeaderboardInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeaderboardInternalService_ServiceDesc, srv)
}

func _LeaderboardInternalService_ListParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardInternalServiceServer).ListParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardInternalService_ListParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardInternalServiceServer).ListParticipants(ctx, req.(*ListParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeaderboardInternalService_ServiceDesc is the grpc.ServiceDesc for LeaderboardInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaderboardInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "challenger.internal.v1.LeaderboardInternalService",
	HandlerType: (*LeaderboardInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListParticipants",
			Handler:    _LeaderboardInternalService_ListParticipants_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "challenger/internalv1/leaderboard.proto",
}
