// Server-to-server read API that challenger-service exposes to
// challenger-notification-service. challenger-service owns this contract; the
// notification service mirrors the file byte-for-byte. A breaking change is a
// new v2 package, never an in-place edit (buf breaking guards this in CI).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: challenger/internalv1/leaderboard.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Participant is one ranked member of a challenge leaderboard.
type Participant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 24-hex ObjectID of the auth-service account.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 1-based leaderboard position. Equal points rank by earlier submission, so
	// every participant has a distinct rank.
	Rank int64 `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	// Best score the participant submitted.
	Points        int64 `protobuf:"varint,3,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_challenger_internalv1_leaderboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_leaderboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_leaderboard_proto_rawDescGZIP(), []int{0}
}

func (x *Participant) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Participant) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Participant) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

// ListParticipantsRequest pages a challenge's participants in rank order (the
// leaderboard order); page_token encodes the leaderboard cursor and is opaque
// to the caller.
type ListParticipantsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 24-hex ObjectID of the challenge.
	ChallengeId string `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// 0 means 1000; larger values are capped at 1000; negative is rejected.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque; empty starts from rank 1.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListParticipantsRequest) Reset() {
	*x = ListParticipantsRequest{}
	mi := &file_challenger_internalv1_leaderboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParticipantsRequest) ProtoMessage() {}

func (x *ListParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_leaderboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParticipantsRequest.ProtoReflect.Descriptor instead.
func (*ListParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_leaderboard_proto_rawDescGZIP(), []int{1}
}

func (x *ListParticipantsRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ListParticipantsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListParticipantsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListParticipantsResponse is one page of participants.
type ListParticipantsResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Participants []*Participant         `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	// Empty when there are no more rows.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Participants in the whole leaderboard, not just this page (O(1)).
	TotalParticipants int64 `protobuf:"varint,3,opt,name=total_participants,json=totalParticipants,proto3" json:"total_participants,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListParticipantsResponse) Reset() {
	*x = ListParticipantsResponse{}
	mi := &file_challenger_internalv1_leaderboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParticipantsResponse) ProtoMessage() {}

func (x *ListParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_leaderboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParticipantsResponse.ProtoReflect.Descriptor instead.
func (*ListParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_leaderboard_proto_rawDescGZIP(), []int{2}
}

func (x *ListParticipantsResponse) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *ListParticipantsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListParticipantsResponse) GetTotalParticipants() int64 {
	if x != nil {
		return x.TotalParticipants
	}
	return 0
}

var File_challenger_internalv1_leaderboard_proto protoreflect.FileDescriptor

const file_challenger_internalv1_leaderboard_proto_rawDesc = "" +
	"\n" +
	"'challenger/internalv1/leaderboard.proto\x12\x16challenger.internal.v1\"R\n" +
	"\vParticipant\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x03R\x04rank\x12\x16\n" +
	"\x06points\x18\x03 \x01(\x03R\x06points\"x\n" +
	"\x17ListParticipantsRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\xba\x01\n" +
	"\x18ListParticipantsResponse\x12G\n" +
	"\fparticipants\x18\x01 \x03(\v2#.challenger.internal.v1.ParticipantR\fparticipants\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12-\n" +
	"\x12total_participants\x18\x03 \x01(\x03R\x11totalParticipants2\x93\x01\n" +
	"\x1aLeaderboardInternalService\x12u\n" +
	"\x10ListParticipants\x12/.challenger.internal.v1.ListParticipantsRequest\x1a0.challenger.internal.v1.ListParticipantsResponseBQZOgithub.com/Everfit-io/challenger-service/proto/challenger/internalv1;internalv1b\x06proto3"

var (
	file_challenger_internalv1_leaderboard_proto_rawDescOnce sync.Once
	file_challenger_internalv1_leaderboard_proto_rawDescData []byte
)

func file_challenger_internalv1_leaderboard_proto_rawDescGZIP() []byte {
	file_challenger_internalv1_leaderboard_proto_rawDescOnce.Do(func() {
		file_challenger_internalv1_leaderboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_challenger_internalv1_leaderboard_proto_rawDesc), len(file_challenger_internalv1_leaderboard_proto_rawDesc)))
	})
	return file_challenger_internalv1_leaderboard_proto_rawDescData
}

var file_challenger_internalv1_leaderboard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_challenger_internalv1_leaderboard_proto_goTypes = []any{
	(*Participant)(nil),              // 0: challenger.internal.v1.Participant
	(*ListParticipantsRequest)(nil),  // 1: challenger.internal.v1.ListParticipantsRequest
	(*ListParticipantsResponse)(nil), // 2: challenger.internal.v1.ListParticipantsResponse
}
var file_challenger_internalv1_leaderboard_proto_depIdxs = []int32{
	0, // 0: challenger.internal.v1.ListParticipantsResponse.participants:type_name -> challenger.internal.v1.Participant
	1, // 1: challenger.internal.v1.LeaderboardInternalService.ListParticipants:input_type -> challenger.internal.v1.ListParticipantsRequest
	2, // 2: challenger.internal.v1.LeaderboardInternalService.ListParticipants:output_type -> challenger.internal.v1.ListParticipantsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_challenger_internalv1_leaderboard_proto_init() }
func file_challenger_internalv1_leaderboard_proto_init() {
	if File_challenger_internalv1_leaderboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_challenger_internalv1_leaderboard_proto_rawDesc), len(file_challenger_internalv1_leaderboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_challenger_internalv1_leaderboard_proto_goTypes,
		DependencyIndexes: file_challenger_internalv1_leaderboard_proto_depIdxs,
		MessageInfos:      file_challenger_internalv1_leaderboard_proto_msgTypes,
	}.Build()
	File_challenger_internalv1_leaderboard_proto = out.File
	file_challenger_internalv1_leaderboard_proto_goTypes = nil
	file_challenger_internalv1_leaderboard_proto_depIdxs = nil
}
