// Server-to-server read API that challenger-service exposes to
// challenger-notification-service. challenger-service owns this contract; the
// notification service mirrors the file byte-for-byte. A breaking change is a
// new v2 package, never an in-place edit (buf breaking guards this in CI).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: challenger/internalv1/profile.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Profile is the notification-facing view of a user.
type Profile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 24-hex ObjectID of the auth-service account.
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// First letter of the last name, upper-cased; empty when there is none.
	LastInitial string `protobuf:"bytes,3,opt,name=last_initial,json=lastInitial,proto3" json:"last_initial,omitempty"`
	// Stored custom avatar, else the assigned default; never empty.
	AvatarUrl           string `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	NotificationEnabled bool   `protobuf:"varint,5,opt,name=notification_enabled,json=notificationEnabled,proto3" json:"notification_enabled,omitempty"`
	Email               string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_challenger_internalv1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Profile) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Profile) GetLastInitial() string {
	if x != nil {
		return x.LastInitial
	}
	return ""
}

func (x *Profile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Profile) GetNotificationEnabled() bool {
	if x != nil {
		return x.NotificationEnabled
	}
	return false
}

func (x *Profile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// ListAccountIDsRequest pages the account ids.
type ListAccountIDsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 0 means 1000; larger values are capped at 1000; negative is rejected.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque; empty starts from the beginning.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountIDsRequest) Reset() {
	*x = ListAccountIDsRequest{}
	mi := &file_challenger_internalv1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountIDsRequest) ProtoMessage() {}

func (x *ListAccountIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountIDsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountIDsRequest) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *ListAccountIDsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAccountIDsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListAccountIDsResponse is one page of account ids.
type ListAccountIDsResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AccountIds []string               `protobuf:"bytes,1,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	// Empty when there are no more rows.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountIDsResponse) Reset() {
	*x = ListAccountIDsResponse{}
	mi := &file_challenger_internalv1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountIDsResponse) ProtoMessage() {}

func (x *ListAccountIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountIDsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountIDsResponse) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_profile_proto_rawDescGZIP(), []int{2}
}

func (x *ListAccountIDsResponse) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

func (x *ListAccountIDsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// BatchGetProfilesRequest names the accounts; at most 500 ids.
type BatchGetProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIds    []string               `protobuf:"bytes,1,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetProfilesRequest) Reset() {
	*x = BatchGetProfilesRequest{}
	mi := &file_challenger_internalv1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetProfilesRequest) ProtoMessage() {}

func (x *BatchGetProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetProfilesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetProfilesRequest) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_profile_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetProfilesRequest) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

// BatchGetProfilesResponse carries the known profiles.
type BatchGetProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetProfilesResponse) Reset() {
	*x = BatchGetProfilesResponse{}
	mi := &file_challenger_internalv1_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetProfilesResponse) ProtoMessage() {}

func (x *BatchGetProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetProfilesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetProfilesResponse) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_profile_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetProfilesResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// FindProfilesByEmailsRequest names the emails; at most 500.
type FindProfilesByEmailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []string               `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindProfilesByEmailsRequest) Reset() {
	*x = FindProfilesByEmailsRequest{}
	mi := &file_challenger_internalv1_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindProfilesByEmailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindProfilesByEmailsRequest) ProtoMessage() {}

func (x *FindProfilesByEmailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindProfilesByEmailsRequest.ProtoReflect.Descriptor instead.
func (*FindProfilesByEmailsRequest) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_profile_proto_rawDescGZIP(), []int{5}
}

func (x *FindProfilesByEmailsRequest) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

// FindProfilesByEmailsResponse carries the matching profiles.
type FindProfilesByEmailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindProfilesByEmailsResponse) Reset() {
	*x = FindProfilesByEmailsResponse{}
	mi := &file_challenger_internalv1_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindProfilesByEmailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindProfilesByEmailsResponse) ProtoMessage() {}

func (x *FindProfilesByEmailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindProfilesByEmailsResponse.ProtoReflect.Descriptor instead.
func (*FindProfilesByEmailsResponse) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_profile_proto_rawDescGZIP(), []int{6}
}

func (x *FindProfilesByEmailsResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_challenger_internalv1_profile_proto protoreflect.FileDescriptor

const file_challenger_internalv1_profile_proto_rawDesc = "" +
	"\n" +
	"#challenger/internalv1/profile.proto\x12\x16challenger.internal.v1\"\xd2\x01\n" +
	"\aProfile\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12!\n" +
	"\flast_initial\x18\x03 \x01(\tR\vlastInitial\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x121\n" +
	"\x14notification_enabled\x18\x05 \x01(\bR\x13notificationEnabled\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\"S\n" +
	"\x15ListAccountIDsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"a\n" +
	"\x16ListAccountIDsResponse\x12\x1f\n" +
	"\vaccount_ids\x18\x01 \x03(\tR\n" +
	"accountIds\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\":\n" +
	"\x17BatchGetProfilesRequest\x12\x1f\n" +
	"\vaccount_ids\x18\x01 \x03(\tR\n" +
	"accountIds\"W\n" +
	"\x18BatchGetProfilesResponse\x12;\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1f.challenger.internal.v1.ProfileR\bprofiles\"5\n" +
	"\x1bFindProfilesByEmailsRequest\x12\x16\n" +
	"\x06emails\x18\x01 \x03(\tR\x06emails\"[\n" +
	"\x1cFindProfilesByEmailsResponse\x12;\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1f.challenger.internal.v1.ProfileR\bprofiles2\x84\x03\n" +
	"\x16ProfileInternalService\x12o\n" +
	"\x0eListAccountIDs\x12-.challenger.internal.v1.ListAccountIDsRequest\x1a..challenger.internal.v1.ListAccountIDsResponse\x12u\n" +
	"\x10BatchGetProfiles\x12/.challenger.internal.v1.BatchGetProfilesRequest\x1a0.challenger.internal.v1.BatchGetProfilesResponse\x12\x81\x01\n" +
	"\x14FindProfilesByEmails\x123.challenger.internal.v1.FindProfilesByEmailsRequest\x1a4.challenger.internal.v1.FindProfilesByEmailsResponseBQZOgithub.com/Everfit-io/challenger-service/proto/challenger/internalv1;internalv1b\x06proto3"

var (
	file_challenger_internalv1_profile_proto_rawDescOnce sync.Once
	file_challenger_internalv1_profile_proto_rawDescData []byte
)

func file_challenger_internalv1_profile_proto_rawDescGZIP() []byte {
	file_challenger_internalv1_profile_proto_rawDescOnce.Do(func() {
		file_challenger_internalv1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_challenger_internalv1_profile_proto_rawDesc), len(file_challenger_internalv1_profile_proto_rawDesc)))
	})
	return file_challenger_internalv1_profile_proto_rawDescData
}

var file_challenger_internalv1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_challenger_internalv1_profile_proto_goTypes = []any{
	(*Profile)(nil),                      // 0: challenger.internal.v1.Profile
	(*ListAccountIDsRequest)(nil),        // 1: challenger.internal.v1.ListAccountIDsRequest
	(*ListAccountIDsResponse)(nil),       // 2: challenger.internal.v1.ListAccountIDsResponse
	(*BatchGetProfilesRequest)(nil),      // 3: challenger.internal.v1.BatchGetProfilesRequest
	(*BatchGetProfilesResponse)(nil),     // 4: challenger.internal.v1.BatchGetProfilesResponse
	(*FindProfilesByEmailsRequest)(nil),  // 5: challenger.internal.v1.FindProfilesByEmailsRequest
	(*FindProfilesByEmailsResponse)(nil), // 6: challenger.internal.v1.FindProfilesByEmailsResponse
}
var file_challenger_internalv1_profile_proto_depIdxs = []int32{
	0, // 0: challenger.internal.v1.BatchGetProfilesResponse.profiles:type_name -> challenger.internal.v1.Profile
	0, // 1: challenger.internal.v1.FindProfilesByEmailsResponse.profiles:type_name -> challenger.internal.v1.Profile
	1, // 2: challenger.internal.v1.ProfileInternalService.ListAccountIDs:input_type -> challenger.internal.v1.ListAccountIDsRequest
	3, // 3: challenger.internal.v1.ProfileInternalService.BatchGetProfiles:input_type -> challenger.internal.v1.BatchGetProfilesRequest
	5, // 4: challenger.internal.v1.ProfileInternalService.FindProfilesByEmails:input_type -> challenger.internal.v1.FindProfilesByEmailsRequest
	2, // 5: challenger.internal.v1.ProfileInternalService.ListAccountIDs:output_type -> challenger.internal.v1.ListAccountIDsResponse
	4, // 6: challenger.internal.v1.ProfileInternalService.BatchGetProfiles:output_type -> challenger.internal.v1.BatchGetProfilesResponse
	6, // 7: challenger.internal.v1.ProfileInternalService.FindProfilesByEmails:output_type -> challenger.internal.v1.FindProfilesByEmailsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_challenger_internalv1_profile_proto_init() }
func file_challenger_internalv1_profile_proto_init() {
	if File_challenger_internalv1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_challenger_internalv1_profile_proto_rawDesc), len(file_challenger_internalv1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_challenger_internalv1_profile_proto_goTypes,
		DependencyIndexes: file_challenger_internalv1_profile_proto_depIdxs,
		MessageInfos:      file_challenger_internalv1_profile_proto_msgTypes,
	}.Build()
	File_challenger_internalv1_profile_proto = out.File
	file_challenger_internalv1_profile_proto_goTypes = nil
	file_challenger_internalv1_profile_proto_depIdxs = nil
}
