// Server-to-server read API that challenger-service exposes to
// challenger-notification-service. challenger-service owns this contract; the
// notification service mirrors the file byte-for-byte. A breaking change is a
// new v2 package, never an in-place edit (buf breaking guards this in CI).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: challenger/internalv1/profile.proto

package internalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProfileInternalService_ListAccountIDs_FullMethodName       = "/challenger.internal.v1.ProfileInternalService/ListAccountIDs"
	ProfileInternalService_BatchGetProfiles_FullMethodName     = "/challenger.internal.v1.ProfileInternalService/BatchGetProfiles"
	ProfileInternalService_FindProfilesByEmails_FullMethodName = "/challenger.internal.v1.ProfileInternalService/FindProfilesByEmails"
)

// ProfileInternalServiceClient is the client API for ProfileInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProfileInternalService serves profile reads for the notification service.
// Every RPC requires the internal-api-secret metadata.
type ProfileInternalServiceClient interface {
	// ListAccountIDs pages every account on account_id ascending, excluding
	// accounts with a pending deletion request. A page can hold fewer than
	// page_size ids (excluded accounts) while next_page_token is set; page on
	// the token, never on the length.
	ListAccountIDs(ctx context.Context, in *ListAccountIDsRequest, opts ...grpc.CallOption) (*ListAccountIDsResponse, error)
	// BatchGetProfiles returns the profiles of up to 500 accounts in request
	// order. Unknown ids are omitted, not an error; duplicates appear once.
	BatchGetProfiles(ctx context.Context, in *BatchGetProfilesRequest, opts ...grpc.CallOption) (*BatchGetProfilesResponse, error)
	// FindProfilesByEmails returns the profiles whose email matches one of up to
	// 500 emails, case-insensitively, in request order. Unknown emails are
	// omitted; an email shared by several accounts returns each of them.
	FindProfilesByEmails(ctx context.Context, in *FindProfilesByEmailsRequest, opts ...grpc.CallOption) (*FindProfilesByEmailsResponse, error)
}

type profileInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileInternalServiceClient(cc grpc.ClientConnInterface) ProfileInternalServiceClient {
	return &profileInternalServiceClient{cc}
}

func (c *profileInternalServiceClient) ListAccountIDs(ctx context.Context, in *ListAccountIDsRequest, opts ...grpc.CallOption) (*ListAccountIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccountIDsResponse)
	err := c.cc.Invoke(ctx, ProfileInternalService_ListAccountIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileInternalServiceClient) BatchGetProfiles(ctx context.Context, in *BatchGetProfilesRequest, opts ...grpc.CallOption) (*BatchGetProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetProfilesResponse)
	err := c.cc.Invoke(ctx, ProfileInternalService_BatchGetProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileInternalServiceClient) FindProfilesByEmails(ctx context.Context, in *FindProfilesByEmailsRequest, opts ...grpc.CallOption) (*FindProfilesByEmailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindProfilesByEmailsResponse)
	err := c.cc.Invoke(ctx, ProfileInternalService_FindProfilesByEmails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileInternalServiceServer is the server API for ProfileInternalService service.
// All implementations must embed UnimplementedProfileInternalServiceServer
// for forward compatibility.
//
// ProfileInternalService serves profile reads for the notification service.
// Every RPC requires the internal-api-secret metadata.
type ProfileInternalServiceServer interface {
	// ListAccountIDs pages every account on account_id ascending, excluding
	// accounts with a pending deletion request. A page can hold fewer than
	// page_size ids (excluded accounts) while next_page_token is set; page on
	// the token, never on the length.
	ListAccountIDs(context.Context, *ListAccountIDsRequest) (*ListAccountIDsResponse, error)
	// BatchGetProfiles returns the profiles of up to 500 accounts in request
	// order. Unknown ids are omitted, not an error; duplicates appear once.
	BatchGetProfiles(context.Context, *BatchGetProfilesRequest) (*BatchGetProfilesResponse, error)
	// FindProfilesByEmails returns the profiles whose email matches one of up to
	// 500 emails, case-insensitively, in request order. Unknown emails are
	// omitted; an email shared by several accounts returns each of them.
	FindProfilesByEmails(context.Context, *FindProfilesByEmailsRequest) (*FindProfilesByEmailsResponse, error)
	mustEmbedUnimplementedProfileInternalServiceServer()
}

// UnimplementedProfileInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfileInternalServiceServer struct{}

func (UnimplementedProfileInternalServiceServer) ListAccountIDs(context.Context, *ListAccountIDsRequest) (*ListAccountIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAccountIDs not implemented")
}
func (UnimplementedProfileInternalServiceServer) BatchGetProfiles(context.Context, *BatchGetProfilesRequest) (*BatchGetProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetProfiles not implemented")
}
func (UnimplementedProfileInternalServiceServer) FindProfilesByEmails(context.Context, *FindProfilesByEmailsRequest) (*FindProfilesByEmailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindProfilesByEmails not implemented")
}
func (UnimplementedProfileInternalServiceServer) mustEmbedUnimplementedProfileInternalServiceServer() {
}
func (UnimplementedProfileInternalServiceServer) testEmbeddedByValue() {}

// UnsafeProfileInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileInternalServiceServer will
// result in compilation errors.
type UnsafeProfileInternalServiceServer interface {
	mustEmbedUnimplementedProfileInternalServiceServer()
}

func RegisterProfileInternalServiceServer(s grpc.ServiceRegistrar, srv ProfileInternalServiceServer) {
	// If the following call panics, it indicates UnimplementedProfileInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfileInternalService_ServiceDesc, srv)
}

func _ProfileInternalService_ListAccountIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileInternalServiceServer).ListAccountIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileInternalService_ListAccountIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileInternalServiceServer).ListAccountIDs(ctx, req.(*ListAccountIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileInternalService_BatchGetProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileInternalServiceServer).BatchGetProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileInternalService_BatchGetProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileInternalServiceServer).BatchGetProfiles(ctx, req.(*BatchGetProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileInternalService_FindProfilesByEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindProfilesByEmailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileInternalServiceServer).FindProfilesByEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileInternalService_FindProfilesByEmails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileInternalServiceServer).FindProfilesByEmails(ctx, req.(*FindProfilesByEmailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileInternalService_ServiceDesc is the grpc.ServiceDesc for ProfileInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "challenger.internal.v1.ProfileInternalService",
	HandlerType: (*ProfileInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAccountIDs",
			Handler:    _ProfileInternalService_ListAccountIDs_Handler,
		},
		{
			MethodName: "BatchGetProfiles",
			Handler:    _ProfileInternalService_BatchGetProfiles_Handler,
		},
		{
			MethodName: "FindProfilesByEmails",
			Handler:    _ProfileInternalService_FindProfilesByEmails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "challenger/internalv1/profile.proto",
}
