// Server-to-server read API that challenger-service exposes to
// challenger-notification-service. challenger-service owns this contract; the
// notification service mirrors the file byte-for-byte. A breaking change is a
// new v2 package, never an in-place edit (buf breaking guards this in CI).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: challenger/internalv1/whitelist.proto

package internalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WhitelistInternalService_ListWhitelistEmails_FullMethodName = "/challenger.internal.v1.WhitelistInternalService/ListWhitelistEmails"
)

// WhitelistInternalServiceClient is the client API for WhitelistInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WhitelistInternalService serves the private-challenge audience.
// Every RPC requires the internal-api-secret metadata.
type WhitelistInternalServiceClient interface {
	// ListWhitelistEmails pages a challenge's whitelist members: every row not
	// removed (is_removed != true), IGNORING is_active — the CMS clears is_active
	// at go-live, so an active-only filter would return nothing when a private
	// challenge's "published" notification fires. Emails come back trimmed and
	// lower-cased, each at most once. A page can hold fewer than page_size
	// emails while next_page_token is set; page on the token.
	ListWhitelistEmails(ctx context.Context, in *ListWhitelistEmailsRequest, opts ...grpc.CallOption) (*ListWhitelistEmailsResponse, error)
}

type whitelistInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWhitelistInternalServiceClient(cc grpc.ClientConnInterface) WhitelistInternalServiceClient {
	return &whitelistInternalServiceClient{cc}
}

func (c *whitelistInternalServiceClient) ListWhitelistEmails(ctx context.Context, in *ListWhitelistEmailsRequest, opts ...grpc.CallOption) (*ListWhitelistEmailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWhitelistEmailsResponse)
	err := c.cc.Invoke(ctx, WhitelistInternalService_ListWhitelistEmails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WhitelistInternalServiceServer is the server API for WhitelistInternalService service.
// All implementations must embed UnimplementedWhitelistInternalServiceServer
// for forward compatibility.
//
// WhitelistInternalService serves the private-challenge audience.
// Every RPC requires the internal-api-secret metadata.
type WhitelistInternalServiceServer interface {
	// ListWhitelistEmails pages a challenge's whitelist members: every row not
	// removed (is_removed != true), IGNORING is_active — the CMS clears is_active
	// at go-live, so an active-only filter would return nothing when a private
	// challenge's "published" notification fires. Emails come back trimmed and
	// lower-cased, each at most once. A page can hold fewer than page_size
	// emails while next_page_token is set; page on the token.
	ListWhitelistEmails(context.Context, *ListWhitelistEmailsRequest) (*ListWhitelistEmailsResponse, error)
	mustEmbedUnimplementedWhitelistInternalServiceServer()
}

// UnimplementedWhitelistInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWhitelistInternalServiceServer struct{}

func (UnimplementedWhitelistInternalServiceServer) ListWhitelistEmails(context.Context, *ListWhitelistEmailsRequest) (*ListWhitelistEmailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWhitelistEmails not implemented")
}
func (UnimplementedWhitelistInternalServiceServer) mustEmbedUnimplementedWhitelistInternalServiceServer() {
}
func (UnimplementedWhitelistInternalServiceServer) testEmbeddedByValue() {}

// UnsafeWhitelistInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WhitelistInternalServiceServer will
// result in compilation errors.
type UnsafeWhitelistInternalServiceServer interface {
	mustEmbedUnimplementedWhitelistInternalServiceServer()
}

func RegisterWhitelistInternalServiceServer(s grpc.ServiceRegistrar, srv WhitelistInternalServiceServer) {
	// If the following call panics, it indicates UnimplementedWhitelistInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WhitelistInternalService_ServiceDesc, srv)
}

func _WhitelistInternalService_ListWhitelistEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWhitelistEmailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhitelistInternalServiceServer).ListWhitelistEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhitelistInternalService_ListWhitelistEmails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhitelistInternalServiceServer).ListWhitelistEmails(ctx, req.(*ListWhitelistEmailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WhitelistInternalService_ServiceDesc is the grpc.ServiceDesc for WhitelistInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WhitelistInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "challenger.internal.v1.WhitelistInternalService",
	HandlerType: (*WhitelistInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWhitelistEmails",
			Handler:    _WhitelistInternalService_ListWhitelistEmails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "challenger/internalv1/whitelist.proto",
}
