// Server-to-server read API that challenger-service exposes to
// challenger-notification-service. challenger-service owns this contract; the
// notification service mirrors the file byte-for-byte. A breaking change is a
// new v2 package, never an in-place edit (buf breaking guards this in CI).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: challenger/internalv1/whitelist.proto

package internalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListWhitelistEmailsRequest pages one challenge's whitelist.
type ListWhitelistEmailsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// 0 means 1000; larger values are capped at 1000; negative is rejected.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque; empty starts from the beginning.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWhitelistEmailsRequest) Reset() {
	*x = ListWhitelistEmailsRequest{}
	mi := &file_challenger_internalv1_whitelist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWhitelistEmailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWhitelistEmailsRequest) ProtoMessage() {}

func (x *ListWhitelistEmailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_whitelist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWhitelistEmailsRequest.ProtoReflect.Descriptor instead.
func (*ListWhitelistEmailsRequest) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_whitelist_proto_rawDescGZIP(), []int{0}
}

func (x *ListWhitelistEmailsRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ListWhitelistEmailsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWhitelistEmailsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListWhitelistEmailsResponse is one page of member emails.
type ListWhitelistEmailsResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Emails []string               `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	// Empty when there are no more rows.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWhitelistEmailsResponse) Reset() {
	*x = ListWhitelistEmailsResponse{}
	mi := &file_challenger_internalv1_whitelist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWhitelistEmailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWhitelistEmailsResponse) ProtoMessage() {}

func (x *ListWhitelistEmailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_challenger_internalv1_whitelist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWhitelistEmailsResponse.ProtoReflect.Descriptor instead.
func (*ListWhitelistEmailsResponse) Descriptor() ([]byte, []int) {
	return file_challenger_internalv1_whitelist_proto_rawDescGZIP(), []int{1}
}

func (x *ListWhitelistEmailsResponse) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *ListWhitelistEmailsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_challenger_internalv1_whitelist_proto protoreflect.FileDescriptor

const file_challenger_internalv1_whitelist_proto_rawDesc = "" +
	"\n" +
	"%challenger/internalv1/whitelist.proto\x12\x16challenger.internal.v1\"{\n" +
	"\x1aListWhitelistEmailsRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"]\n" +
	"\x1bListWhitelistEmailsResponse\x12\x16\n" +
	"\x06emails\x18\x01 \x03(\tR\x06emails\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x9a\x01\n" +
	"\x18WhitelistInternalService\x12~\n" +
	"\x13ListWhitelistEmails\x122.challenger.internal.v1.ListWhitelistEmailsRequest\x1a3.challenger.internal.v1.ListWhitelistEmailsResponseBQZOgithub.com/Everfit-io/challenger-service/proto/challenger/internalv1;internalv1b\x06proto3"

var (
	file_challenger_internalv1_whitelist_proto_rawDescOnce sync.Once
	file_challenger_internalv1_whitelist_proto_rawDescData []byte
)

func file_challenger_internalv1_whitelist_proto_rawDescGZIP() []byte {
	file_challenger_internalv1_whitelist_proto_rawDescOnce.Do(func() {
		file_challenger_internalv1_whitelist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_challenger_internalv1_whitelist_proto_rawDesc), len(file_challenger_internalv1_whitelist_proto_rawDesc)))
	})
	return file_challenger_internalv1_whitelist_proto_rawDescData
}

var file_challenger_internalv1_whitelist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_challenger_internalv1_whitelist_proto_goTypes = []any{
	(*ListWhitelistEmailsRequest)(nil),  // 0: challenger.internal.v1.ListWhitelistEmailsRequest
	(*ListWhitelistEmailsResponse)(nil), // 1: challenger.internal.v1.ListWhitelistEmailsResponse
}
var file_challenger_internalv1_whitelist_proto_depIdxs = []int32{
	0, // 0: challenger.internal.v1.WhitelistInternalService.ListWhitelistEmails:input_type -> challenger.internal.v1.ListWhitelistEmailsRequest
	1, // 1: challenger.internal.v1.WhitelistInternalService.ListWhitelistEmails:output_type -> challenger.internal.v1.ListWhitelistEmailsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_challenger_internalv1_whitelist_proto_init() }
func file_challenger_internalv1_whitelist_proto_init() {
	if File_challenger_internalv1_whitelist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_challenger_internalv1_whitelist_proto_rawDesc), len(file_challenger_internalv1_whitelist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_challenger_internalv1_whitelist_proto_goTypes,
		DependencyIndexes: file_challenger_internalv1_whitelist_proto_depIdxs,
		MessageInfos:      file_challenger_internalv1_whitelist_proto_msgTypes,
	}.Build()
	File_challenger_internalv1_whitelist_proto = out.File
	file_challenger_internalv1_whitelist_proto_goTypes = nil
	file_challenger_internalv1_whitelist_proto_depIdxs = nil
}
